spring:
  datasource:
    url: jdbc:mysql://localhost:3306/KafkaMessageDB
    username: root
    password: Qwerty1995@
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092